# 应用名称
spring:
  application:
    name: demo1
# 开发时禁用缓存
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/shopping
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1

mybatis:
  mapper-locations: classpath*:/mappers/*Mapper.xml

server:
  port: 8080
com:
  czklps:
    best:
      wishes: "端午节快乐"
